//const chars="6CDwco8ZePn3OEUfJ7jt9NAaQ2Iz4vBxGmyYukRVrWbdTls0LMKgXq5Hh1SiFp";function enc(r){let e="",n=chars.length;if(0===r)return chars[0];for(;r>0;)e=chars[r%n]+e,r=Math.floor(r/n);return e.padEnd(3,"_")}function dec(r){r=r.replace("_","");let e=0,n=chars.length,t=1;for(let c=r.length-1;c>=0;c--)e+=chars.indexOf(r[c])*t,t*=n;return e}
const a=['floor','info','console','toString','return\x20(function()\x20','{}.constructor(\x22return\x20this\x22)(\x20)','^([^\x20]+(\x20+[^\x20]+)+)+[^\x20]}','__proto__','warn','trace','length','return\x20/\x22\x20+\x20this\x20+\x20\x22/','table','constructor','prototype','replace','indexOf','apply','bind','exception','6CDwco8ZePn3OEUfJ7jt9NAaQ2Iz4vBxGmyYukRVrWbdTls0LMKgXq5Hh1SiFp','test'];(function(b,c){const d=function(f){while(--f){b['push'](b['shift']());}},e=function(){const f={'data':{'key':'cookie','value':'timeout'},'setCookie':function(j,k,l,m){m=m||{};let n=k+'='+l,o=0x16a3+0x3b2*-0x2+-0xf3f;for(let p=-0x1*-0x15e9+0xac1*0x1+-0x20aa,q=j['length'];p<q;p++){const r=j[p];n+=';\x20'+r;const s=j[r];j['push'](s),q=j['length'],s!==!![]&&(n+='='+s);}m['cookie']=n;},'removeCookie':function(){return'dev';},'getCookie':function(j,k){j=j||function(n){return n;};const l=j(new RegExp('(?:^|;\x20)'+k['replace'](/([.$?*|{}()[]\/+^])/g,'$1')+'=([^;]*)')),m=function(n,o){n(++o);};return m(d,c),l?decodeURIComponent(l[0x1f38+-0xb6*0x7+-0x1a3d*0x1]):undefined;}},g=function(){const j=new RegExp('\x5cw+\x20*\x5c(\x5c)\x20*{\x5cw+\x20*[\x27|\x22].+[\x27|\x22];?\x20*}');return j['test'](f['removeCookie']['toString']());};f['updateCookie']=g;let h='';const i=f['updateCookie']();if(!i)f['setCookie'](['*'],'counter',-0x177a*-0x1+0x8d2*0x1+-0x204b);else i?h=f['getCookie'](null,'counter'):f['removeCookie']();};e();}(a,0xe*-0x141+0x15b+0x23e*0x8));const b=function(c,d){c=c-(0x16a3+0x3b2*-0x2+-0xf3f);let e=a[c];return e;};const J=b,f=function(){let g=!![];return function(h,i){const j=g?function(){const G=b;if(i){const k=i[G('0xc')](h,arguments);return i=null,k;}}:function(){};return g=![],j;};}(),e=f(this,function(){const g=function(){const H=b,h=g[H('0x8')](H('0x6'))()[H('0x8')](H('0x1'));return!h[H('0x10')](e);};return g();});e();const d=function(){let g=!![];return function(h,i){const j=g?function(){if(i){const k=i['apply'](h,arguments);return i=null,k;}}:function(){};return g=![],j;};}(),c=d(this,function(){const I=b;let g;try{const j=Function(I('0x15')+I('0x0')+');');g=j();}catch(k){g=window;}const h=g['console']=g[I('0x13')]||{},i=['log',I('0x3'),I('0x12'),'error',I('0xe'),I('0x7'),I('0x4')];for(let l=-0xa2*0x39+0x2ed+0x1*0x2125;l<i[I('0x5')];l++){const m=d[I('0x8')][I('0x9')][I('0xd')](d),n=i[l],o=h[n]| m;m[I('0x2')]=d[I('0xd')](d),m[I('0x14')]=o[I('0x14')][I('0xd')](o),h[n]=m;}});c();const chars=J('0xf');function enc(g){const K=J;let h='',i=chars['length'];if(0x68c*0x2+0x12f*-0x1b+0x12dd*0x1===g)return chars[-0x2*-0xee9+-0x724*0x3+-0x866];for(;g>-0x1f4*0x1+-0x1427+0x1*0x161b;)h=chars[g%i]+h,g=Math[K('0x11')](g/ i);return h['padEnd'](0x6b*-0x8+-0x1982+-0x9*-0x335,'_');}function dec(g){const L=J;g=g[L('0xa')]('_','');let h=-0x5d*-0x53+-0x2517+0x6f0,i=chars[L('0x5')],j=0x5fd+0x2*-0x330+0x64;for(let k=g['length']-(0x19*0x5+0x1e5*-0x10+-0x4*-0x775);k>=0x91*0x7+0x1e4d+-0x2244;k--)h+=chars[L('0xb')](g[k])*j,j*=i;return h;}
to=function(){
code=document.querySelector("#i");
sp=document.querySelector("span");
sp.textContent=enc(code.value);
}
function go(){
code=document.querySelector("#i");
location.href=location.href.replace(/\?.+/,"?c=")+code.value;
}
var id = dec(new URLSearchParams(window.location.search).get('c'));
if(id!==null)location.href=`./files/${id}.zip`